apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/minikube-tutorial/pipeline:f2e47532590f3556b72504e9496a995e0a237f3a
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
