apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/minikube-tutorial/pipeline:0dd08a9718e5c3cabd14bfee95fe1cb5ce1b1b55
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
